version: "2.2"

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ES_VERSION: ${STACK_VERSION}
    image: lukenhatbui/vi_elasticsearch:${ELASTIC_STACK_VERSION}
